# Data preprocessing 

This ipynb script returns 2 preprocessed dataframes (df and df_eval). Df is used for testing the different methods for seperating reviews and our baseline models whereas df_eval is used for the evaluation of the different review seperation methods and baseline models.

## Importing the relevant csv files:

In [2]:
import pandas as pd

#Load datasets
reviews = pd.read_csv("../data/reviews83325.csv")
places = pd.read_csv("../data/Tripadvisor.csv")

print("Reviews shape:", reviews.shape)
print("Places shape:", places.shape)

C:\Users\Maxim\AppData\Local\Temp\ipykernel_23716\797032139.py:4: DtypeWarning: Columns (15,16,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews = pd.read_csv("../data/reviews83325.csv")

Reviews shape: (340385, 21)
Places shape: (3761, 60)

In [3]:
reviews.head()

,id,idplace,titre,idauteur,review,note,date_review,date_visit,langue,published_platform,...,subratings,machine_translated,machine_translatable,owner_id,owner_langue,owner_date_review,owner_connection,owner_responder,owner_response,owner_title
0,771569620,188467,February,F645CC9429E8A40EB1F5A487780EC683,Personally I think it is the most beautiful sq...,5,23/9/2020 11:14:11,2020-02,en,Desktop,...,[],False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,769814072,188467,Nice green square,AFFB511F21DF819776CB2F8013034382,We walked through this lovely park but did not...,4,11/9/2020 07:52:32,2019-10,en,Desktop,...,[],False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,758953508,188467,A Treasure in Paris,9262311F3378F8CC4709DD4D92380278,We come back to this huge square every time we...,5,5/7/2020 03:16:32,2019-10,en,Desktop,...,[],False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,755705747,188467,A place to take a breath from exploring Paris.,836BAA8786B81033412B950CF5BDA70C,The most beautiful square in Paris has a stran...,5,31/5/2020 19:36:17,2019-06,en,Desktop,...,[],False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,750396525,188467,Beautiful and elegant,8FEC7B1C9034428EFF3BF8728B036829,"Lovely architecture, looks different again to ...",4,11/3/2020 06:16:38,2020-03,en,Desktop,...,[],False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
places.head()

,id,idTrip,fromId,nom,url,rating,nbAvis,nbAvisRecupere,latitude,longitude,...,ap_exclusion,ap_inclusions,ap_introduction,ap_primary_supplier_attraction_id,ap_primary_supplier_subtype,ap_primary_ta_geo_id,ap_product_code,ap_product_highlights,ap_product_text,ap_raw
0,188467,187147.0,187070.0,Place des Vosges,https://www.tripadvisor.fr/Attraction_Review-g...,4.108407,5663,5664.0,48.855614,2.365553,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,188468,187147.0,187070.0,Rue des Francs Bourgeois,https://www.tripadvisor.fr/Attraction_Review-g...,3.316532,73,73.0,48.858140,2.359880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,188470,187147.0,NaN,Village Saint-Paul,https://www.tripadvisor.fr/Attraction_Review-g...,3.017118,98,98.0,48.853733,2.361295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,188471,187147.0,187144.0,Au Passe-partout,https://www.tripadvisor.fr/Attraction_Review-g...,2.743157,2,2.0,48.853470,2.361600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,188472,187147.0,187070.0,Cloître des Billettes,https://www.tripadvisor.fr/Attraction_Review-g...,2.942987,23,23.0,48.858000,2.354980,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340385 entries, 0 to 340384
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    340385 non-null  int64
 1   idplace               340385 non-null  int64
 2   titre                 340382 non-null  object
 3   idauteur              339726 non-null  object
 4   review                340385 non-null  object
 5   note                  340385 non-null  int64
 6   date_review           340385 non-null  object
 7   date_visit            321147 non-null  object
 8   langue                340385 non-null  object
 9   published_platform    340385 non-null  object
 10  typeReview            340385 non-null  object
 11  subratings            340385 non-null  object
 12  machine_translated    340385 non-null  bool
 13  machine_translatable  340385 non-null  bool
 14  owner_id              39641 non-null   float64
 15  owner_langue          39641 non-null   object
 16  owner_date_review     39641 non-null   object
 17  owner_connection      39640 non-null   object
 18  owner_responder       39397 non-null   object
 19  owner_response        39641 non-null   object
 20  owner_title           39641 non-null   object
dtypes: bool(2), float64(1), int64(3), object(15)
memory usage: 50.0+ MB

In [6]:
places.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3761 entries, 0 to 3760
Data columns (total 60 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   id                                 3761 non-null   int64
 1   idTrip                             3754 non-null   float64
 2   fromId                             201 non-null    float64
 3   nom                                3761 non-null   object
 4   url                                3697 non-null   object
 5   rating                             3661 non-null   float64
 6   nbAvis                             3761 non-null   int64
 7   nbAvisRecupere                     2344 non-null   float64
 8   latitude                           3761 non-null   float64
 9   longitude                          3761 non-null   float64
 10  typeR                              3761 non-null   object
 11  adresse                            1028 non-null   object
 12  priceRange                         586 non-null    object
 13  closed                             1092 non-null   float64
 14  hotelType                          57 non-null     object
 15  hotelStyle                         0 non-null      float64
 16  hotelStars                         0 non-null      float64
 17  hotelRoomNumber                    3761 non-null   int64
 18  hotelNoteEmplacement               0 non-null      float64
 19  hotelNoteProprete                  0 non-null      float64
 20  hotelNoteService                   0 non-null      float64
 21  HotelNoteQualitePrix               0 non-null      float64
 22  hoteldistance                      58 non-null     float64
 23  hotelbearing                       64 non-null     object
 24  restaurantTypeCuisine              518 non-null    object
 25  restaurantDietaryRestrictions      232 non-null    object
 26  restaurantMeals                    0 non-null      float64
 27  restaurantFeatures                 0 non-null      float64
 28  restaurantNoteCuisine              0 non-null      float64
 29  restaurantNoteService              0 non-null      float64
 30  restaurantNoteQualitePrix          0 non-null      float64
 31  restaurantNoteAmbiance             0 non-null      float64
 32  activiteType                       3021 non-null   object
 33  activiteSubCategorie               405 non-null    object
 34  activiteSubType                    405 non-null    object
 35  website                            768 non-null    object
 36  nbScanReview                       0 non-null      float64
 37  dateLastScanReviews                2344 non-null   object
 38  shape_gid                          3761 non-null   int64
 39  gadm36_gid                         3761 non-null   int64
 40  hotelprice                         2983 non-null   object
 41  hotelBookingID                     45 non-null     float64
 42  restaurantSubcategory              484 non-null    object
 43  restaurantType                     623 non-null    object
 44  ap_additional_info                 2669 non-null   object
 45  ap_age_band_list                   2669 non-null   object
 46  ap_attraction_ids                  2669 non-null   object
 47  ap_booking_question_list           2669 non-null   object
 48  ap_bubble_rating_integer           2669 non-null   float64
 49  ap_duration                        2669 non-null   object
 50  ap_exclusion                       2103 non-null   object
 51  ap_inclusions                      2667 non-null   object
 52  ap_introduction                    2669 non-null   object
 53  ap_primary_supplier_attraction_id  2669 non-null   float64
 54  ap_primary_supplier_subtype        2631 non-null   object
 55  ap_primary_ta_geo_id               2669 non-null   float64
 56  ap_product_code                    2669 non-null   object
 57  ap_product_highlights              1121 non-null   object
 58  ap_product_text                    2669 non-null   object
 59  ap_raw                             2669 non-null   object
dtypes: float64(25), int64(5), object(30)
memory usage: 1.7+ MB

## Removing unecessary columns:

Based on the results from reviews.info and places.info, we can directly elimenate the following null columns:

- hotelStyle
- hotelStars 
- hotelNoteEmplacement
- hotelNoteProprete
- hotelNoteService
- HotelNoteQualitePrix
- restaurantMeals
- restaurantFeatures
- restaurantNoteCuisine
- restaurantNoteService
- resturantNoteQualitePrix
- restaurantNoteAmbiance
- nbScanReview

In [7]:
drop_columns=['hotelStyle','hotelStars','hotelNoteEmplacement','hotelNoteProprete','hotelNoteService','HotelNoteQualitePrix','restaurantMeals',
              'restaurantFeatures','restaurantNoteCuisine','restaurantNoteService','restaurantNoteQualitePrix','restaurantNoteAmbiance','nbScanReview']

places = places.drop(labels=drop_columns,axis=1)

places.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3761 entries, 0 to 3760
Data columns (total 47 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   id                                 3761 non-null   int64
 1   idTrip                             3754 non-null   float64
 2   fromId                             201 non-null    float64
 3   nom                                3761 non-null   object
 4   url                                3697 non-null   object
 5   rating                             3661 non-null   float64
 6   nbAvis                             3761 non-null   int64
 7   nbAvisRecupere                     2344 non-null   float64
 8   latitude                           3761 non-null   float64
 9   longitude                          3761 non-null   float64
 10  typeR                              3761 non-null   object
 11  adresse                            1028 non-null   object
 12  priceRange                         586 non-null    object
 13  closed                             1092 non-null   float64
 14  hotelType                          57 non-null     object
 15  hotelRoomNumber                    3761 non-null   int64
 16  hoteldistance                      58 non-null     float64
 17  hotelbearing                       64 non-null     object
 18  restaurantTypeCuisine              518 non-null    object
 19  restaurantDietaryRestrictions      232 non-null    object
 20  activiteType                       3021 non-null   object
 21  activiteSubCategorie               405 non-null    object
 22  activiteSubType                    405 non-null    object
 23  website                            768 non-null    object
 24  dateLastScanReviews                2344 non-null   object
 25  shape_gid                          3761 non-null   int64
 26  gadm36_gid                         3761 non-null   int64
 27  hotelprice                         2983 non-null   object
 28  hotelBookingID                     45 non-null     float64
 29  restaurantSubcategory              484 non-null    object
 30  restaurantType                     623 non-null    object
 31  ap_additional_info                 2669 non-null   object
 32  ap_age_band_list                   2669 non-null   object
 33  ap_attraction_ids                  2669 non-null   object
 34  ap_booking_question_list           2669 non-null   object
 35  ap_bubble_rating_integer           2669 non-null   float64
 36  ap_duration                        2669 non-null   object
 37  ap_exclusion                       2103 non-null   object
 38  ap_inclusions                      2667 non-null   object
 39  ap_introduction                    2669 non-null   object
 40  ap_primary_supplier_attraction_id  2669 non-null   float64
 41  ap_primary_supplier_subtype        2631 non-null   object
 42  ap_primary_ta_geo_id               2669 non-null   float64
 43  ap_product_code                    2669 non-null   object
 44  ap_product_highlights              1121 non-null   object
 45  ap_product_text                    2669 non-null   object
 46  ap_raw                             2669 non-null   object
dtypes: float64(12), int64(5), object(30)
memory usage: 1.3+ MB

## Keeping only english reviews, removing HTML artifacts and strange characters, and normalizing accents:

English reviews:

In [8]:
# Most important first: what is in langue?
lang_counts = reviews["langue"].astype(str).str.lower().str.strip().value_counts(dropna=False)
print(lang_counts.head(30))
print("\nUnique langue values:", lang_counts.shape[0])

langue
en      153071
fr       99078
it       22912
es       21768
pt       19521
ru        5463
de        5237
ja        4124
nl        2835
ko        1133
sv         920
da         666
el         570
tr         570
pl         490
zhtw       488
no         426
zhcn       408
iw         185
cs          81
th          81
ar          78
fi          76
hu          73
in          61
sr          31
sk          29
vi          10
Name: count, dtype: int64

Unique langue values: 28

Since the english reviews represent roughly 45% of the dataset, we will only work with english reviews from here on out

In [9]:
import pandas as pd
import re

print("Total reviews:", len(reviews))

reviews_en = reviews[reviews["langue"].astype(str).str.lower().str.strip().eq("en")].copy()

print("English reviews:", len(reviews_en))
print("Percentage kept:", len(reviews_en) / len(reviews))

print("\nLangue distribution (english df):")
print(reviews_en["langue"].value_counts(dropna=False).head(10))

Total reviews: 340385
English reviews: 153071
Percentage kept: 0.44969960485920357

Langue distribution (english df):
langue
en    153071
Name: count, dtype: int64

HTML artifacts:

In [10]:
s = reviews_en["review"].fillna("").astype(str)

has_html_tags = s.str.contains(r"<[^>]+>", regex=True)
has_html_entities = s.str.contains(r"&(?:nbsp|amp|quot|lt|gt|#\d+|#x[0-9a-fA-F]+);", regex=True)

print("English rows:", len(reviews_en))
print("HTML tags count:", int(has_html_tags.sum()), "pct:", float(has_html_tags.mean()))
print("HTML entities count:", int(has_html_entities.sum()), "pct:", float(has_html_entities.mean()))

print("\nLangue values inside HTML-tag examples (should all be 'en'):")
print(reviews_en.loc[has_html_tags, "langue"].value_counts(dropna=False))

print("\nExamples with HTML tags:")
display(reviews_en.loc[has_html_tags, ["idplace", "langue", "review"]].head(10))

print("\nExamples with HTML entities:")
display(reviews_en.loc[has_html_entities, ["idplace", "langue", "review"]].head(10))

English rows: 153071
HTML tags count: 10 pct: 6.532916097758556e-05
HTML entities count: 2 pct: 1.3065832195517112e-05

Langue values inside HTML-tag examples (should all be 'en'):
langue
en    10
Name: count, dtype: int64

Examples with HTML tags:

         idplace langue                                             review
29532     188679     en  I have visited the <a class='inlineAdmedialink...
90000     208440     en  We just spent a couple hours there, and were q...
90065     208440     en  I happened upon this place by accident while i...
152835    718129     en  This is almost a hole-in-the-wall eating place...
195377   1035226     en  Very Smart restaurant..wonderfull wine and foo...
196433   1035629     en  Okay, we were wandering away from Notre Dame o...
210115   1524417     en  Excellent experience. My son (13) and I were v...
244408   2397509     en  It was Easter sunday so there were a lot of pe...
305984  11453183     en  We had the best time walking around and seeing...
332668  15126566     en  Emilie was a delight. By the time we met up wi...

Examples with HTML entities:

        idplace langue                                             review
99884    235555     en  We visited the Hotel in April-May 2001.  The m...
167011   719581     en  simply a &quot;must&quot; .........rush there ...

These rates are negligible, so we do not apply aggressive HTML cleaning.
- We only apply minimal normalization (unescape entities + normalize whitespace),
- which is cheap and keeps semantics intact for BM25 + dense embeddings.

In [11]:
import html
import re

# Minimal normalization only (NOT aggressive cleaning)
reviews_en["text"] = reviews_en["review"].fillna("").astype(str)

# Decode entities like &quot; -> "
reviews_en["text"] = reviews_en["text"].apply(html.unescape)

# Remove tags only if present (affects ~10 rows)
reviews_en.loc[has_html_tags, "text"] = reviews_en.loc[has_html_tags, "text"].str.replace(r"<[^>]+>", " ", regex=True)

# Normalize whitespace
reviews_en["text"] = reviews_en["text"].str.replace(r"\s+", " ", regex=True).str.strip()

print("Using English review text with minimal normalization (entities decoded; rare tags removed).")

Using English review text with minimal normalization (entities decoded; rare tags removed).

In [12]:
# Verify HTML artifacts are gone (or near-zero) in the cleaned text
s2 = reviews_en["text"].fillna("").astype(str)

tags_after = s2.str.contains(r"<[^>]+>", regex=True)
entities_after = s2.str.contains(r"&(?:nbsp|amp|quot|lt|gt|#\d+|#x[0-9a-fA-F]+);", regex=True)

print("After minimal normalization:")
print("HTML tags count:", int(tags_after.sum()), "pct:", float(tags_after.mean()))
print("HTML entities count:", int(entities_after.sum()), "pct:", float(entities_after.mean()))

After minimal normalization:
HTML tags count: 0 pct: 0.0
HTML entities count: 0 pct: 0.0

Strange characters:

In [13]:
# Replacement char and NBSP
has_replacement = s.str.contains("�", regex=False)
has_nbsp = s.str.contains("\u00A0", regex=False)  # non-breaking space

# Zero-width chars: ZWSP, ZWNJ, ZWJ, BOM
zero_width_re = r"[\u200B\u200C\u200D\uFEFF]"
has_zero_width = s.str.contains(zero_width_re, regex=True)

# Control chars (excluding normal whitespace)
control_re = r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]"
has_control = s.str.contains(control_re, regex=True)

print("Contains '�' %:", has_replacement.mean())
print("Contains NBSP (\\u00A0) %:", has_nbsp.mean())
print("Contains zero-width %:", has_zero_width.mean())
print("Contains control chars %:", has_control.mean())

print("\nExamples with strange chars:")
mask = has_replacement | has_nbsp | has_zero_width | has_control
display(reviews_en.loc[mask, ["idplace", "review"]].head(10))

Contains '�' %: 1.3065832195517112e-05
Contains NBSP (\u00A0) %: 0.0007643511834377511
Contains zero-width %: 0.00020252039903051526
Contains control chars %: 2.6131664391034225e-05

Examples with strange chars:

       idplace                                             review
1169    188467  This 3 Michelin stars spot had missed my itine...
2597    188467  Place des Vosges was once meant to be the roya...
5081    188467  THE wonderful square of Paris. Just imagine li...
23537   188679  Notre Dame is a special place for me. This vis...
37685   188679  We visited the cathedral as a side note and no...
42546   188679  Many important ebents took placr in Notre Dame...
43395   188679  The cathedral is a masterpiece. Truly magnefic...
44043   188679  This church is an architectural gem, it was de...
44296   188679  It's a pure scam. Deceitful and misleading  in...
46462   188679  This is one of Paris most beautiful attraction...

Strange/unprintable characters were rare (<0.1%). We applied a minimal cleanup (NBSP, zero-width, control characters, replacement char) to avoid tokenization issues, without altering semantics.

In [14]:
import re

# Work on the cleaned column you already created
# (raw column stays in reviews_en["review"])
reviews_en["text"] = reviews_en["text"].fillna("").astype(str)

# Remove zero-width characters (ZWSP, ZWNJ, ZWJ, BOM)
reviews_en["text"] = reviews_en["text"].str.replace(r"[\u200B\u200C\u200D\uFEFF]", "", regex=True)

# Remove ASCII control characters (excluding normal spaces)
reviews_en["text"] = reviews_en["text"].str.replace(r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]", " ", regex=True)

# Replace non-breaking spaces just in case any remain
reviews_en["text"] = reviews_en["text"].str.replace("\u00A0", " ", regex=False)

# Replace the Unicode replacement character � (very rare) with a space
reviews_en["text"] = reviews_en["text"].str.replace("�", " ", regex=False)

# Normalize whitespace again
reviews_en["text"] = reviews_en["text"].str.replace(r"\s+", " ", regex=True).str.strip()

print("Applied minimal strange-character cleanup on reviews_en['text'].")

Applied minimal strange-character cleanup on reviews_en['text'].

In [15]:
s_check = reviews_en["text"].fillna("").astype(str)

print("After cleanup:")
print("Contains '�' %:", s_check.str.contains("�", regex=False).mean())
print("Contains NBSP (\\u00A0) %:", s_check.str.contains("\u00A0", regex=False).mean())
print("Contains zero-width %:", s_check.str.contains(r"[\u200B\u200C\u200D\uFEFF]", regex=True).mean())
print("Contains control chars %:", s_check.str.contains(r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]", regex=True).mean())

After cleanup:
Contains '�' %: 0.0
Contains NBSP (\u00A0) %: 0.0
Contains zero-width %: 0.0
Contains control chars %: 0.0

Accents, no need since we used english reviews only.

## Creating our models dataset and evaluation dataset

df_models:

In [16]:
reviews_en.info()

<class 'pandas.core.frame.DataFrame'>
Index: 153071 entries, 0 to 340384
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    153071 non-null  int64
 1   idplace               153071 non-null  int64
 2   titre                 153070 non-null  object
 3   idauteur              153061 non-null  object
 4   review                153071 non-null  object
 5   note                  153071 non-null  int64
 6   date_review           153071 non-null  object
 7   date_visit            142576 non-null  object
 8   langue                153071 non-null  object
 9   published_platform    153071 non-null  object
 10  typeReview            153071 non-null  object
 11  subratings            153071 non-null  object
 12  machine_translated    153071 non-null  bool
 13  machine_translatable  153071 non-null  bool
 14  owner_id              19136 non-null   float64
 15  owner_langue          19136 non-null   object
 16  owner_date_review     19136 non-null   object
 17  owner_connection      19136 non-null   object
 18  owner_responder       19056 non-null   object
 19  owner_response        19136 non-null   object
 20  owner_title           19136 non-null   object
 21  text                  153071 non-null  object
dtypes: bool(2), float64(1), int64(3), object(16)
memory usage: 24.8+ MB

In [17]:
df_models = reviews_en[["id", "idplace", "text","note"]].copy()
df_models.columns = ["review_id", "place_id", "review_text","score"]
print(df_models.head())
print(df_models.shape)

   review_id  place_id                                        review_text  \
0  771569620    188467  Personally I think it is the most beautiful sq...
1  769814072    188467  We walked through this lovely park but did not...
2  758953508    188467  We come back to this huge square every time we...
3  755705747    188467  The most beautiful square in Paris has a stran...
4  750396525    188467  Lovely architecture, looks different again to ...

   score
0      5
1      4
2      5
3      5
4      4
(153071, 4)

In [18]:
n_places = df_models["place_id"].nunique()
n_reviews = len(df_models)
print("reviews:", n_reviews, "\nunique places:", n_places)

# check missing/empty
print("missing text:", df_models["review_text"].isna().sum())
print("empty text:", (df_models["review_text"].astype(str).str.strip() == "").sum())

reviews: 153071
unique places: 1835
missing text: 0
empty text: 0

df_eval:

In [19]:
places.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3761 entries, 0 to 3760
Data columns (total 47 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   id                                 3761 non-null   int64
 1   idTrip                             3754 non-null   float64
 2   fromId                             201 non-null    float64
 3   nom                                3761 non-null   object
 4   url                                3697 non-null   object
 5   rating                             3661 non-null   float64
 6   nbAvis                             3761 non-null   int64
 7   nbAvisRecupere                     2344 non-null   float64
 8   latitude                           3761 non-null   float64
 9   longitude                          3761 non-null   float64
 10  typeR                              3761 non-null   object
 11  adresse                            1028 non-null   object
 12  priceRange                         586 non-null    object
 13  closed                             1092 non-null   float64
 14  hotelType                          57 non-null     object
 15  hotelRoomNumber                    3761 non-null   int64
 16  hoteldistance                      58 non-null     float64
 17  hotelbearing                       64 non-null     object
 18  restaurantTypeCuisine              518 non-null    object
 19  restaurantDietaryRestrictions      232 non-null    object
 20  activiteType                       3021 non-null   object
 21  activiteSubCategorie               405 non-null    object
 22  activiteSubType                    405 non-null    object
 23  website                            768 non-null    object
 24  dateLastScanReviews                2344 non-null   object
 25  shape_gid                          3761 non-null   int64
 26  gadm36_gid                         3761 non-null   int64
 27  hotelprice                         2983 non-null   object
 28  hotelBookingID                     45 non-null     float64
 29  restaurantSubcategory              484 non-null    object
 30  restaurantType                     623 non-null    object
 31  ap_additional_info                 2669 non-null   object
 32  ap_age_band_list                   2669 non-null   object
 33  ap_attraction_ids                  2669 non-null   object
 34  ap_booking_question_list           2669 non-null   object
 35  ap_bubble_rating_integer           2669 non-null   float64
 36  ap_duration                        2669 non-null   object
 37  ap_exclusion                       2103 non-null   object
 38  ap_inclusions                      2667 non-null   object
 39  ap_introduction                    2669 non-null   object
 40  ap_primary_supplier_attraction_id  2669 non-null   float64
 41  ap_primary_supplier_subtype        2631 non-null   object
 42  ap_primary_ta_geo_id               2669 non-null   float64
 43  ap_product_code                    2669 non-null   object
 44  ap_product_highlights              1121 non-null   object
 45  ap_product_text                    2669 non-null   object
 46  ap_raw                             2669 non-null   object
dtypes: float64(12), int64(5), object(30)
memory usage: 1.3+ MB

We want to keep all the information in palces for later evaluation, however, we will only keep places which have english reviews.

In [24]:
df_eval=places
english_place_ids = reviews_en["idplace"].dropna().unique()
df_eval = places[places["id"].isin(english_place_ids)].copy()
print("Original places:", len(places))
print("df_eval (EN places only):", len(df_eval))

Original places: 3761
df_eval (EN places only): 1835

At this stage, we deliberately separate the pipeline into two datasets with different roles. df_models is a lightweight, review-level dataframe containing only (review_id, place_id, review_text, score); it is the working input used by all review-selection scripts because it keeps the raw textual signal in the simplest possible format and makes it easy to implement strategies like Top-K longest/medium reviews, sentiment-balanced sampling (using score if needed), sentence-level filtering, TF-IDF word budgets, and summarization—without being tied to any specific retrieval model. In parallel, df_eval is kept as the full places table (all metadata columns) and is intentionally not polluted with review text: its purpose is to provide a stable ground-truth reference for later evaluation, where relevance can be defined using one or multiple criteria (e.g., same broad type typeR for level-1 relevance, and finer fields such as subcategory/cuisine/hotel type for level-2, or even additional criteria like price range, rating bucket, or location). The next steps are therefore to: 
- (1) implement the different “meaningful review” selection methods that transform df_models into a place-level corpus (place_id → selected_text)
- (2) run the retrieval models (BM25, TF-IDF, dense, hybrid, reranking) on these corpora 
- (3) compute ranking metrics (Precision@K, Recall@K, MRR, HitRate@K, nDCG, plus the level-1/level-2 ranking error) using df_eval as the relevance source, allowing a clean and fair comparison across the 35 method×model combinations.

In [26]:
set_models = set(df_models["place_id"].unique())
set_eval   = set(df_eval["id"].unique())

print("Missing in eval:", len(set_models - set_eval))
print("Missing in models:", len(set_eval - set_models))

Missing in eval: 0
Missing in models: 0

## Saving datasets as parquet files

In [25]:
import os
os.makedirs("../data/processed_data", exist_ok=True)

# Save
df_models.to_parquet("../data/processed_data/df_models.parquet", index=False)
df_eval.to_parquet("../data/processed_data/df_eval.parquet", index=False)

print("Saved as parquet.")

Saved as parquet.